name: Documentation
on:
  workflow_run:
    workflows: ["Evaluation"]
    types:
      - completed

jobs:
  vocabulary:
    name: SOMA Vocabulary
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/vocab/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Workflow A Run ID
        id: set_run_id
        run: echo "TRIGGER_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV

      - name: Print Workflow A Run ID
        run: echo "The run ID of Workflow A is $TRIGGER_RUN_ID"

      - name: Download OWL file
        uses: actions/download-artifact@v4
        with:
          name: owl-files-for-documentation
          path: ./build/owl/current
          run-id: ${{ env.TRIGGER_RUN_ID }}

      - name: Copy
        run: |
          cp ./Makefile ../../
          cp ./SOMA-vocabulary.tex ../../
          cp ./owl_reader.py ../../

      - name: Build
        uses: ./.github/actions/pythonlatex
        with:
          args: make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SOMA Vocabulary
          path: ./SOMA-vocabulary.pdf

  handbook:
    name: NEEM Handbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        uses: docker://blang/latex:ubuntu
        with:
          args: make -f ./docs/NEEM-handbook/Makefile

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: NEEM Handbook
          path: ./docs/NEEM-handbook/main.pdf
